name: WorldConverter
main: AlicanCopur\WorldConverter
api: [3.9.0]
version: 1.0
author: AlicanCopur
description: A plugin for convert Anvil format worlds to PMAnvil.
commands:
  convert:
    description: Convert Anvil worlds to PMAnvil.
    permission: worldupdater.convert
permissions:
  worldupdater.convert:
    default: op
